# Unraid HDD temp export config

VIRTIOFS_TAG="vm-unraid-hdd"
MOUNT_POINT="/mnt/proxmox-fan"
OUTPUT_FILE="/mnt/proxmox-fan/hdd_temp_status.env"

ONLY_ROTATIONAL_DISKS="yes"
SMART_STANDBY_MODE="yes"
HOT_TEMP_C=40

LOG_FILE="/var/log/hdd_temp_export_virtiofs.log"
